# Generated by Django 5.0.1 on 2024-03-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
