# Generated by Django 5.0.1 on 2024-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_ave',
            field=models.IntegerField(null=True),
        ),
    ]
