# Generated by Django 5.0.1 on 2024-02-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_ave',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
